import type { Metadata } from "next";
import "./globals.css";
import Header from "@/layout/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header />
        <main className="max-w-3xl mx-auto p-6">{children}</main>
      </body>
    </html>
  );
}
